language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

before_install:
  - chmod +x gradlew

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - ./gradlew build --scan -s

after_script:
  - "yes"